# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: driverkt.github.io
tagline: ""
description: ""
url: https://driverkt.github.io
baseurl: /

author:
  name: "Kevin Driver"
  url: https://github.com/driverkt

plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde
